<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="T_ManualMode" Id="{339991d4-876f-4668-acda-cc2d207d93a2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK T_ManualMode IMPLEMENTS I_PackMLMode
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="T_ManualMode">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>