<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="EquipmentModule" Id="{2e44d4e8-09ab-435d-a0e1-458f7bc1a6a4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EquipmentModule EXTENDS FB_PackML_BaseModule
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EquipmentModule">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>