<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="T_GetComponentCompareResultsTrue" Id="{e9a4bf6b-918e-4c6c-8f6a-5af5f3d4eba8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK T_GetComponentCompareResultsTrue EXTENDS T_UnitTestBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TestFinished();]]></ST>
    </Implementation>
    <LineIds Name="T_GetComponentCompareResultsTrue">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>