<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="T_RemoveComponentAtIndexRemovesItem" Id="{a5ac6aae-d815-4031-8abd-dd6bd35c8542}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK T_RemoveComponentAtIndexRemovesItem EXTENDS T_UnitTestBase
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TestFinished();]]></ST>
    </Implementation>
    <LineIds Name="T_RemoveComponentAtIndexRemovesItem">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>