<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="T_GripperManualMode" Id="{77faa915-6ddf-4717-8420-89f4dde5a135}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK T_GripperManualMode EXTENDS T_NamedBase IMPLEMENTS I_PackMode
VAR
	_gripper : I_GripperModule;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Initialise" Id="{2026c3b5-73a5-47a5-92b0-1284bcfe0625}">
      <Declaration><![CDATA[METHOD Initialise
VAR_INPUT
	Gripper : I_GripperModule;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_gripper := Gripper;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="T_GripperManualMode">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="T_GripperManualMode.Initialise">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>