<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="T_GripperMaintenanceMode" Id="{c2fd17b7-5c19-4cd9-8362-9cd1c9e29854}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK T_GripperMaintenanceMode EXTENDS T_NamedBase IMPLEMENTS I_PackMode
VAR
	_gripper : I_GripperModule;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Initialise" Id="{f69b160e-7628-4189-a9af-5b278fb8bfd4}">
      <Declaration><![CDATA[METHOD Initialise
VAR_INPUT
	Gripper : I_GripperModule;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_gripper := Gripper;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="T_GripperMaintenanceMode">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="T_GripperMaintenanceMode.Initialise">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>