<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="T_ContainsComponentCompareResultTrue" Id="{e60208ed-9066-4494-9717-1e67b98003a8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK T_ContainsComponentCompareResultTrue EXTENDS T_UnitTestBase
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TestFinished();]]></ST>
    </Implementation>
    <LineIds Name="T_ContainsComponentCompareResultTrue">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>