<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="T_CylinderComponent" Id="{9c58672d-2584-427d-923c-5ff0608b9288}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK T_CylinderComponent EXTENDS FB_ComponentBase
VAR
	_cylinder : I_Cylinder;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="GenericInitialise" Id="{be4c08c4-f43f-4504-99bd-20dd1643bb74}">
      <Declaration><![CDATA[METHOD GenericInitialise
VAR_INPUT
	Cylinder : I_Cylinder; 
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_cylinder := Cylinder;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="T_CylinderComponent">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="T_CylinderComponent.GenericInitialise">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>