<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="T_Cylinder" Id="{d09c98af-cbe5-4c84-9fab-f7b1717b81db}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK T_Cylinder EXTENDS T_NamedBase IMPLEMENTS I_Cylinder
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="T_Cylinder">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>