<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="T_AddComponentAddedToList" Id="{0a8b6a35-5a1f-409c-9210-a2cfd61be5f4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK T_AddComponentAddedToList EXTENDS T_UnitTestBase
VAR
  list : T_ComponentsCollection;
  newComponent : T_ComponentMock;
  result : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[result := list.AddComponent(newComponent);

assertion.AssertEquals_BOOL(TRUE, result, 'list.AddComponent(newComponent);');
TestFinished();
]]></ST>
    </Implementation>
    <LineIds Name="T_AddComponentAddedToList">
      <LineId Id="15" Count="0" />
      <LineId Id="20" Count="2" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>