<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="T_ModuleCollectionAnyErrorReturnErrorTrue" Id="{9951032a-54ac-43f8-b233-8a2aa0319dd9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK T_ModuleCollectionAnyErrorReturnErrorTrue EXTENDS T_UnitTestBase
VAR
  list : T_SubModuleCollection;
  newModule, newModule2 : T_SubModuleMock; 
  actual1, actual2 : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Arrange
list.AddModule(newModule);
list.AddModule(newModule2);

//Act
list.CyclicLogic();
newModule._error := TRUE;

//Assert
actual1 := list.AnyError;

assertion.AssertEquals_BOOL(TRUE, actual1, 'list.AnyError;');
TestFinished();]]></ST>
    </Implementation>
    <LineIds Name="T_ModuleCollectionAnyErrorReturnErrorTrue">
      <LineId Id="14" Count="4" />
      <LineId Id="9" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="21" Count="4" />
      <LineId Id="20" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>