<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="T_ModuleCollectionInitialisedSuccess" Id="{49bf7dae-95bb-46d1-be88-668cfa4a2532}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK T_ModuleCollectionInitialisedSuccess EXTENDS T_UnitTestBase
VAR
  list : T_SubModuleCollection;
  newModule, newModule2 : T_SubModuleMock; 
  actual1, actual2 : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Arrange
list.AddModule(newModule);
list.AddModule(newModule2);

//Act
list.CyclicLogic();

//Assert
actual1 := list.InitialisedAll;

assertion.AssertEquals_BOOL(TRUE, actual1, 'actual1 := list.InitialisedAll');
TestFinished();]]></ST>
    </Implementation>
    <LineIds Name="T_ModuleCollectionInitialisedSuccess">
      <LineId Id="38" Count="0" />
      <LineId Id="52" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="39" Count="0" />
      <LineId Id="24" Count="0" />
      <LineId Id="27" Count="0" />
      <LineId Id="41" Count="0" />
      <LineId Id="40" Count="0" />
      <LineId Id="33" Count="0" />
      <LineId Id="29" Count="1" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>